name: Snapshot Build

on:
  push:
    branches: [ develop, dev ]
  workflow_dispatch:

jobs:
  snapshot:
    name: Build Snapshot
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get current version
        id: version
        run: echo "version=$(./gradlew --console plain --quiet currentVersion -Prelease.quiet)" >> $GITHUB_OUTPUT

      - name: Build project
        run: ./gradlew build shadowJar

      - name: Create snapshot release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: snapshot-${{ github.run_number }}
          name: Snapshot Build #${{ github.run_number }}
          body: |
            Snapshot build from commit ${{ github.sha }}
            
            Version: ${{ steps.version.outputs.version }}
            Branch: ${{ github.ref_name }}
            
            This is an automated snapshot build for testing purposes.
          files: build/libs/*.jar
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 